server:
  port: 9090
spring:
  datasource:
    username: root #todo 你需要配置
    password: hsp #todo 你需要配置
    url: jdbc:mysql://192.168.75.128:3306/boot_shop?useSSL=false&amp;useUnicode=true&amp;characterEncoding=UTF-8 #todo 你需要配置
    druid:
      stat-view-servlet:
        enabled: true
        login-username: root #todo 你需要配置
        login-password: hsp #todo 你需要配置，
        reset-enable: false
        allow:
      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
          config:
            delete-allow: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    hiddenmethod:
      filter:
        enabled: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
  type-aliases-package: com.kivy0000.beans  #类型别名bean
#  mapper-locations: #指定mapper地址，使用mapperScan注解替代，也可用默认地址（/mapper/**/*.xml
mailutil:
  default-sender: kivy0000@126.com   #todo 你需要配置
  default-password: JZTWIYARSFGITIRG   #todo 你需要配置